name: Internship Dashboard Pipeline

on:
  schedule:
    - cron: "0 2 * * *"   # Ejecutar todos los días a las 02:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Internship Dashboard pipeline
        run: python run_all.py

      - name: Upload pipeline outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-output
          path: data/OUTPUT/
