name: Portfolio Demo (no real data)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Dry run (no API calls)
        env:
          DEMO_MODE: "1"
        run: |
          echo "Running in DEMO_MODE – no external requests."
          python run_all.py --dry-run || echo "Add --dry-run handling if needed."
      # No artifact upload here
