name: Internship Dashboard Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the pipeline
      - name: Run Internship Dashboard pipeline
        run: python run_all.py

      # 5. Upload output data as an artifact
      - name: Upload pipeline outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-output
          path: data/OUTPUT/
